// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAROZ_Abex9z0z3dENu4I7T85afadjAZbE',
    appId: '1:947299951031:web:5cd2c371a422bb2c474832',
    messagingSenderId: '947299951031',
    projectId: 'aidoctor-8db93',
    authDomain: 'aidoctor-8db93.firebaseapp.com',
    storageBucket: 'aidoctor-8db93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBSW2tjsgJmrO_IE3KO0vTW_spsOpbufk',
    appId: '1:947299951031:android:64fca341ef69467b474832',
    messagingSenderId: '947299951031',
    projectId: 'aidoctor-8db93',
    storageBucket: 'aidoctor-8db93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-Mss0WNfGmF5NrxSnR5v6XAVFEbroW8',
    appId: '1:947299951031:ios:b889fa72dadc8e49474832',
    messagingSenderId: '947299951031',
    projectId: 'aidoctor-8db93',
    storageBucket: 'aidoctor-8db93.firebasestorage.app',
    iosBundleId: 'com.example.aidocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-Mss0WNfGmF5NrxSnR5v6XAVFEbroW8',
    appId: '1:947299951031:ios:b889fa72dadc8e49474832',
    messagingSenderId: '947299951031',
    projectId: 'aidoctor-8db93',
    storageBucket: 'aidoctor-8db93.firebasestorage.app',
    iosBundleId: 'com.example.aidocApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAROZ_Abex9z0z3dENu4I7T85afadjAZbE',
    appId: '1:947299951031:web:05044844bf704370474832',
    messagingSenderId: '947299951031',
    projectId: 'aidoctor-8db93',
    authDomain: 'aidoctor-8db93.firebaseapp.com',
    storageBucket: 'aidoctor-8db93.firebasestorage.app',
  );
}
